language: php
dist: trusty
sudo: false

cache:
  directories:
  - $HOME/.composer/cache
  - vendor

git:
  depth: 5

matrix:
  include:
  - dist: precise
    php: 5.3
  - php: 5.4
  - php: 5.5
  - php: 5.6
  - php: 7.0
  - php: 7.1
  - php: 7.2
  - php: 7.3
  - php: 7.4
  - php: 7.4
    env:
      - PHPSTAN=1
  - php: nightly

  fast_finish: true
  allow_failures:
  - php: nightly

before_script:
- composer install --no-interaction --no-progress --prefer-dist --ansi

script:
  - if [[ $PHPSTAN == "1" ]]; then
      composer require --dev phpstan/phpstan:^0.12 phpstan/phpstan-phpunit phpunit/phpunit:^7.5 --no-update &&
      composer update phpstan/* phpunit/* sebastian/* --with-all-dependencies &&
      vendor/bin/phpstan analyse;
    else
      vendor/bin/phpunit --coverage-clover=coverage.xml;
    fi

after_success:
- bash <(curl -s https://codecov.io/bash)
